### ISSUE TITLE
observable chart of country data

### ISSUE THREAD

**Issue by benjiqq** [covid19-data/covid19-data#13]
example in observable how to create simple chart, based on output/cntry_stat.json

https://observablehq.com/@benjyz/covid-chart-alpha

**Comment by yy** [comment]
Very cool! Do you want to use https://github.com/covid19-data/covid19-data/blob/master/output/cntry_stat_owid.json instead? It also contains country code information (but not the recovered numbers).

**Comment by yy** [comment]
Hey it's listed here: https://github.com/covid19-data/covid19-data/blob/master/README.md#daily-case-data-in-json
