### ISSUE TITLE
country data

### ISSUE THREAD

**Issue by benjiqq** [covid19-data/covid19-data#14]
last update of this file is 3 days ago. not sure how to update/generate it

https://github.com/covid19-data/covid19-data/blob/master/output/cntry_stat.json

**Comment by yy** [comment]
Thanks. I've changed the data source from JHU CSSE GitHub repo to Our World in Data (WHO). So, https://github.com/covid19-data/covid19-data/blob/master/output/cntry_stat_owid.json is up-to-date. Maybe I should remove this file.

**Comment by benjiqq** [comment]
Updated to owid.

US last day is old

![1603](https://user-images.githubusercontent.com/5390515/76750243-80247780-67b0-11ea-985f-99225d27a809.png)

**Comment by yy** [comment]
It's consistent with WHO's 3/15 report: https://www.who.int/docs/default-source/coronaviruse/situation-reports/20200315-sitrep-55-covid-19.pdf?sfvrsn=33daa5cb_6

Actually CDC number is also quite small: https://www.cdc.gov/coronavirus/2019-ncov/cases-in-us.html

I think aggregation is not done quickly enough. We can choose to override with Wikipedia data.: https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_the_United_States  See #1

**Comment by yy** [comment]
Shall we close this issue? We can discuss about US data here: #1

**Comment by yy** [comment]
@benjyz see #19. We have two versions, one with US data overrided with wikipedia data.
