### ISSUE TITLE
Country Code for Kosovo - where's the ISO norm?

### ISSUE THREAD

**Issue by Bost** [covid19-data/covid19-data#16]
Could you please point me to the ISO norm which defines the 3-letter code for Kosovo as `XKX`. All I can find is just the 2-letter code norm. (That says `XK`.) Thank you.

**Comment by yy** [comment]
https://github.com/covid19-data/covid19-data/blob/955d909522e62c40a9164d625ccfd31022c22118/data_sources/worldbank_population_data/API_SP.POP.TOTL_DS2_en_csv_v2_821007.csv#L265

Sorry the file was not in the repo originally. It's from Worldbank.

**Comment by Bost** [comment]
I think we don't understand each other.
I mean this [ISO Norm](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#XK) defines 2-letter code for Kosovo as `XK`:
```
The code XK is being used by the European Commission,[24] the IMF, and SWIFT,[25] CLDR and other organizations as a temporary country code for Kosovo.[26]
```

So far everything's OK. 
But(!) Kosovo is nowhere to be found in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3 ! :(
So can you tell me please where, in which document from the Worldbank, have you found that `XKX` is for Kosovo?

Besides, I really think that it is a strong imperative for us to use only the ISO Norms and the ISO Norms only! The business of the Worldbank money and such. This is definitely not a standardisation authority of any kind.

**Comment by yy** [comment]
Ok, it seems like it doesn't have the code yet? https://en.wikipedia.org/wiki/Talk:ISO_3166-1_alpha-3#KOS/KVA 

Worldbank data is from https://data.worldbank.org/indicator/SP.POP.TOTL and they have "XKX".
