### ISSUE TITLE
Data errors

### ISSUE THREAD

**Issue by helske** [covid19-data/covid19-data#5]
I found some errors in the data, as WHO has errors in their data as well:

Data on Norway is lagging one day: https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_Norway. 

Finland is missing multiple days (they are just imputed as no new cases, in WHO data some rows are completely missing).: https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_Finland

**Comment by helske** [comment]
My guess is that some of the issues with these multi-country datasets are that if governments/authorities do not report their new cases in time, instead of reporting lack of data, WHO shows zero new cases, and moves on next day?

**Comment by yy** [comment]
My plan is to keep the WHO dataset, and then create country-level (more up-to-date) datasets so that we can override each country to create the most comprehensive and up-to-date datasets down the pipeline.

**Comment by yy** [comment]
See #20 

In the meantime, if anyone can create a CSV file in this format https://github.com/covid19-data/covid19-data/blob/master/output/cases/cases_WHO.csv, I can easily merge it with WHO data. @helske @awtimmering
