### ISSUE TITLE
Data issues for 3/21

### ISSUE THREAD

**Issue by TruffleClock** [covid19-data/covid19-data#51]
HI, I'm reporting 2 issues:

1) The data for 3/21 in Switzerland and France did not get updated from the previous day, other countries may have issues too but I noticed those

2) The data in _cntry_stat_owid.json_ appears to lag 1 day behind _cntry_stat_ecdc_wp.json_

**Comment by yy** [comment]
Thanks! Will look into it.

**Comment by yy** [comment]
I think #52 is fixing it.
