### ISSUE TITLE
Spanish flu fatality rate is likely too low

### ISSUE THREAD

**Issue by buyske** [covid19-data/covid19-data#62]
This article https://www.wired.com/story/covid-19-is-nothing-like-the-spanish-flu/ points out that the 2.5% CFR for Spanish flu is inconsistent with the estimated number of deaths and the world population. "There were 1.8 billion people in 1918. To make 50 million deaths compatible with a 2.5 percent CFR would require at least two billion infections—more than the number of people that existed at the time." The author of the piece suggests 6% to 8%

**Comment by yy** [comment]
Thanks for the pointer. Will incorporate this information to the visualization.

**Comment by yy** [comment]
https://observablehq.com/@yy/covid-19-fatality-rate
